"""Update maintenance schema for Phase 7

Revision ID: 34333d23bcda
Revises: 4bd0014f7cb4
Create Date: 2026-07-12 15:36:24.773317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34333d23bcda'
down_revision: Union[str, Sequence[str], None] = '4bd0014f7cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enums
    priority_enum = sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='maintenance_priority_enum')
    priority_enum.create(op.get_bind(), checkfirst=True)
    
    type_enum = sa.Enum('OIL_CHANGE', 'ENGINE_SERVICE', 'BRAKE_SERVICE', 'TYRE_REPLACEMENT', 'BATTERY_REPLACEMENT', 'INSPECTION', 'INSURANCE', 'REGISTRATION', 'ACCIDENT_REPAIR', 'BODY_WORK', 'ELECTRICAL', 'TRANSMISSION', 'OTHER', name='maintenance_type_enum')
    type_enum.create(op.get_bind(), checkfirst=True)

    # Add CANCELLED to maintenancestatus
    op.execute("ALTER TYPE maintenancestatus ADD VALUE IF NOT EXISTS 'CANCELLED'")
    
    op.add_column('maintenance_records', sa.Column('priority', priority_enum, nullable=False, server_default='MEDIUM'))
    op.add_column('maintenance_records', sa.Column('mechanic_name', sa.String(), nullable=True))
    op.add_column('maintenance_records', sa.Column('invoice_number', sa.String(), nullable=True))
    op.add_column('maintenance_records', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('maintenance_records', sa.Column('estimated_cost', sa.Float(), nullable=True))
    op.add_column('maintenance_records', sa.Column('actual_cost', sa.Float(), nullable=True))
    op.add_column('maintenance_records', sa.Column('expected_completion', sa.DateTime(timezone=True), nullable=True))
    op.add_column('maintenance_records', sa.Column('completed_date', sa.DateTime(timezone=True), nullable=True))
    
    # Drop and recreate maintenance_type to avoid casting issues
    op.drop_column('maintenance_records', 'maintenance_type')
    op.add_column('maintenance_records', sa.Column('maintenance_type', type_enum, nullable=False, server_default='OTHER'))
    
    op.alter_column('maintenance_records', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('maintenance_records', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('maintenance_records', 'cost')
    op.drop_column('maintenance_records', 'end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_records', sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('maintenance_records', sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('maintenance_records', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('maintenance_records', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('maintenance_records', 'maintenance_type',
               existing_type=sa.Enum('OIL_CHANGE', 'ENGINE_SERVICE', 'BRAKE_SERVICE', 'TYRE_REPLACEMENT', 'BATTERY_REPLACEMENT', 'INSPECTION', 'INSURANCE', 'REGISTRATION', 'ACCIDENT_REPAIR', 'BODY_WORK', 'ELECTRICAL', 'TRANSMISSION', 'OTHER', name='maintenance_type_enum'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('maintenance_records', 'completed_date')
    op.drop_column('maintenance_records', 'expected_completion')
    op.drop_column('maintenance_records', 'actual_cost')
    op.drop_column('maintenance_records', 'estimated_cost')
    op.drop_column('maintenance_records', 'remarks')
    op.drop_column('maintenance_records', 'invoice_number')
    op.drop_column('maintenance_records', 'mechanic_name')
    op.drop_column('maintenance_records', 'priority')
    # ### end Alembic commands ###
