"""add deleted_at to maintenance_records

Revision ID: 4fec9b446ef3
Revises: eb7e7519c5fb
Create Date: 2026-07-16 19:57:16.482693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fec9b446ef3'
down_revision: Union[str, Sequence[str], None] = 'eb7e7519c5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_records', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance_records', 'deleted_at')
    # ### end Alembic commands ###
