"""add_daily_snapshot

Revision ID: 7dce4e2c6b79
Revises: 4fec9b446ef3
Create Date: 2026-07-17 15:48:50.353422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dce4e2c6b79'
down_revision: Union[str, Sequence[str], None] = '4fec9b446ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_snapshots',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'metric_name', name='uq_daily_snapshot_date_metric')
    )
    op.create_index(op.f('ix_daily_snapshots_date'), 'daily_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_daily_snapshots_metric_name'), 'daily_snapshots', ['metric_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_snapshots_metric_name'), table_name='daily_snapshots')
    op.drop_index(op.f('ix_daily_snapshots_date'), table_name='daily_snapshots')
    op.drop_table('daily_snapshots')
    # ### end Alembic commands ###
