"""Update expense schema for Phase 8

Revision ID: eb7e7519c5fb
Revises: 34333d23bcda
Create Date: 2026-07-12 15:46:42.315456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb7e7519c5fb'
down_revision: Union[str, Sequence[str], None] = '34333d23bcda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUMs
    fuel_type_enum = sa.Enum('DIESEL', 'PETROL', 'CNG', 'ELECTRIC', 'HYBRID', 'OTHER', name='fuel_type_enum')
    fuel_type_enum.create(op.get_bind(), checkfirst=True)
    
    payment_method_enum = sa.Enum('CASH', 'CARD', 'UPI', 'COMPANY_ACCOUNT', 'OTHER', name='payment_method_enum')
    payment_method_enum.create(op.get_bind(), checkfirst=True)
    
    # Alter ExpenseType
    op.execute("ALTER TYPE expensetype ADD VALUE IF NOT EXISTS 'INSURANCE'")
    op.execute("ALTER TYPE expensetype ADD VALUE IF NOT EXISTS 'REGISTRATION'")
    op.execute("ALTER TYPE expensetype ADD VALUE IF NOT EXISTS 'TYRES'")
    op.execute("ALTER TYPE expensetype ADD VALUE IF NOT EXISTS 'BATTERY'")
    op.execute("ALTER TYPE expensetype ADD VALUE IF NOT EXISTS 'CLEANING'")
    op.execute("ALTER TYPE expensetype ADD VALUE IF NOT EXISTS 'MISCELLANEOUS'")

    op.add_column('expenses', sa.Column('vendor', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('invoice_number', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('payment_method', payment_method_enum, nullable=False, server_default='CASH'))
    op.add_column('expenses', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('expenses', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('expenses', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('expenses', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('expenses', 'expense_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('expenses', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_foreign_key(None, 'expenses', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.add_column('fuel_logs', sa.Column('fuel_type', fuel_type_enum, nullable=False, server_default='DIESEL'))
    op.add_column('fuel_logs', sa.Column('invoice_number', sa.String(), nullable=True))
    op.add_column('fuel_logs', sa.Column('payment_method', payment_method_enum, nullable=False, server_default='CASH'))
    op.add_column('fuel_logs', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('fuel_logs', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('fuel_logs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fuel_logs', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('fuel_logs', 'liters',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('fuel_logs', 'price_per_liter',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('fuel_logs', 'total_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('fuel_logs', 'filled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('fuel_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_foreign_key(None, 'fuel_logs', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.add_column('trips', sa.Column('trip_fuel_cost', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('trips', sa.Column('trip_expenses', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('trips', sa.Column('trip_operational_cost', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('vehicles', sa.Column('total_fuel_cost', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('vehicles', sa.Column('total_maintenance_cost', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('vehicles', sa.Column('total_other_expenses', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('vehicles', sa.Column('total_operational_cost', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'total_operational_cost')
    op.drop_column('vehicles', 'total_other_expenses')
    op.drop_column('vehicles', 'total_maintenance_cost')
    op.drop_column('vehicles', 'total_fuel_cost')
    op.drop_column('trips', 'trip_operational_cost')
    op.drop_column('trips', 'trip_expenses')
    op.drop_column('trips', 'trip_fuel_cost')
    op.drop_constraint(None, 'fuel_logs', type_='foreignkey')
    op.alter_column('fuel_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('fuel_logs', 'filled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('fuel_logs', 'total_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('fuel_logs', 'price_per_liter',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('fuel_logs', 'liters',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('fuel_logs', 'updated_at')
    op.drop_column('fuel_logs', 'deleted_at')
    op.drop_column('fuel_logs', 'updated_by')
    op.drop_column('fuel_logs', 'remarks')
    op.drop_column('fuel_logs', 'payment_method')
    op.drop_column('fuel_logs', 'invoice_number')
    op.drop_column('fuel_logs', 'fuel_type')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.alter_column('expenses', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('expenses', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('expenses', 'expense_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('expenses', 'updated_at')
    op.drop_column('expenses', 'deleted_at')
    op.drop_column('expenses', 'updated_by')
    op.drop_column('expenses', 'remarks')
    op.drop_column('expenses', 'payment_method')
    op.drop_column('expenses', 'invoice_number')
    op.drop_column('expenses', 'vendor')
    # ### end Alembic commands ###
